[package]
name = "rust-web3_meets_wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
hex-literal = "0.3.4"
tokio = "1.19.2"
web3 = "0.18.0"
